### PR TITLE
Fix some udev errors

### PR DESCRIPTION
**Pull request by sgallag-insta**
Partial fix for: https://github.com/wayblueorg/wayblue/issues/64

### CODE REVIEW

**Review by RoyalOughtness — APPROVED** [review]

**Comment by RoyalOughtness** [comment]
@sgallag-insta looks like this can be reverted now? https://copr.fedorainfracloud.org/coprs/ublue-os/staging/build/8160678/

**Comment by sgallag-insta** [comment]
@qoijjj Per my comment [here](https://github.com/wayblueorg/wayblue/issues/64#issuecomment-2425529957), I think the build was actually always correct. For some reason the repo we are adding is giving us the wrong version. I suspect there's a problem with the URL (maybe `OS_VERSION` is doing something funky?)

**Comment by RoyalOughtness** [comment]
@sgallag-insta I'm confused then, isn't our repo configuration identical to bluefin's? It would be good to get to the bottom of this

**Comment by sgallag-insta** [comment]
@qoijjj I've spent a bit more time looking into this and I too am really confused. I can confirm that the latest build does have the correct file and we seem to be calling the correct URL but when we try to install it from the ublue staging repo it isn't getting the latest (even though the repo seems to contain the latest build).

Also while bluefin's install process is different, I haven't noticed anything we need to do differently

**Pull request merged**
