### PR TITLE
chore: Switch signing to use `/etc/` & use `jq` instead of `yq`

### PR DESCRIPTION
**Pull request by fiftydinar**
Related: https://github.com/secureblue/secureblue/pull/657

### CODE REVIEW

**Comment by rehashedsalt** [comment]
Any particular reason we should switch from `yq` to `jq` here? I'm not opinionated, just looking for reasoning

*E*: I do appreciate the ability to use args instead of relying on shell envvar markup.

**Comment by RoyalOughtness** [comment]
@rehashedsalt it's one less dep to include, for one thing. if this is all that needs it, might as well swap it out

**Comment by RoyalOughtness** [comment]
also @rehashedsalt the way bluebuild includes it currently is by installing it directly into /usr/bin, which could potentially cause issues if for some reason someone needs the rpm yq layered

**Comment by fiftydinar** [comment]
> the way bluebuild includes it currently is by installing it directly into /usr/bin, which could potentially cause issues if for some reason someone needs the rpm yq layered

We don't include `yq` in BlueBuild anymore. We switched fully to `jq` there, hence why I made this PR.
We did that after you made the issue where `yq` lagged a bit on security updates + the unconditional copy to `/usr/bin/` as you mentioned.

**Review by RoyalOughtness — DISMISSED** [review]

**Review by RoyalOughtness — APPROVED** [review]

**Pull request merged**
